version: "3.3"

networks:
  net:
    driver: bridge
services:
  postgres_loms:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: 5432
    volumes:
      - .:/var/lib/postgresql/data/loms
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d loms"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  postgres_checkout:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: 5433
    volumes:
      - .:/var/lib/postgresql/data/checkout
    ports:
      - 5433:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d checkout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "50051:50051"
    depends_on:
      - postgres_checkout
    networks:
      - net
    restart: unless-stopped
  loms:
    image: loms
    build: ./loms/
    ports:
      - "50052:50052"
    depends_on:
      - postgres_loms
    networks:
      - net
    restart: unless-stopped

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"


