-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS OrderUsers (
    orderID bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS OrderUsers;
-- +goose StatementEnd
